#!/usr/bin/env node
// Batch 11: agentic-coding / AI-tooling vocabulary — ML-systems internals
// (FlashAttention, PagedAttention, GQA/MQA/MLA, GPTQ/AWQ/NF4, FSDP, ZeRO…),
// coding agents (CodeAct, Reflexion, Toolformer, subagent, swe-agent, vibe-coding),
// new models/products (Codestral, Pixtral, Nemotron, EXAONE, Aya, Recraft, Veo…),
// and modern dev tooling (mise, pixi, oxlint, ratatui, watchexec, chezmoi, knip…).
// Discovered + adversarially source-verified via multi-agent workflow, then hand-reviewed.
// Columns: word, ipa, respelling_us, alt_ipa, alt_respelling_us,
//          source_url, source_label, category, confidence, notes
import { readFileSync, writeFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const repoRoot = join(dirname(fileURLToPath(import.meta.url)), "..");
const tsvPath = join(repoRoot, "data", "pronunciations.tsv");

const rows = [
  ["rdma","/ˌɑːr ˌdiː ˌɛm ˈeɪ/","ar dee em ay","","","https://en.wikipedia.org/wiki/Remote_direct_memory_access","Wikipedia — Remote direct memory access","acronym","community-consensus","Initialism for Remote Direct Memory Access — read as four separate letters R-D-M-A (ar-dee-em-AY), not as a word. Backbone of multi-node GPU training (GPUDirect RDMA, RoCE, InfiniBand). Note the related RoCE is spoken \"rocky\", but RDMA itself stays letter-by-letter."],
  ["Molmo","/ˈmɑlmoʊ/","mahl moh","/ˈmoʊlmoʊ/","mohl moh","https://github.com/allenai/molmo","allenai/molmo GitHub README (\"Molmo: Multimodal Open Language Model\")","product","community-consensus","Ai2 (Allen Institute for AI) open multimodal model family, 2024; Molmo 2 in 2025-2026. Name is a portmanteau acronym: M(ultimodal) O(pen) L(anguage) Mo(del) = MOL + Mo. STRESS first syllable: MOL-moh, where MOL rhymes with \"doll\" (short o, same OL as in sibling OLMo) and \"moh\" is the long-o of \"Model\". Easy to confuse with sibling OLMo (\"OL-mo\") and to mispronounce as long-o MOHL-moh (like \"mole\") — the short-o MOL form follows the acronym. Respelling uses \"mahl\" because macOS say reads \"mol\"/\"moll\"/\"mohl\" all as long-o; only \"mahl\" yields the short-o. No official creator pronunciation FAQ found, so community-consensus."],
  ["flashinfer","/ˈflæʃˌɪnfɜːr/","flash in fur","","","https://github.com/flashinfer-ai/flashinfer","FlashInfer GitHub repository (flashinfer-ai/flashinfer)","project","community-consensus","Portmanteau of flash + inference; a high-performance GPU kernel/attention library for LLM serving (MLSys 2025, arXiv 2501.01005), a default backend in vLLM/SGLang/TensorRT-LLM. The infer element is from inference and is said like the verb infer (in-FUR), not in-fur as guessed from spelling. STRESS: primary on first syllable, FLASH-in-fur. No creator-quoted pronunciation found, so community-consensus."],
  ["vibe-coding","/ˈvaɪb ˌkoʊdɪŋ/","vybe koh ding","","","https://en.wikipedia.org/wiki/Vibe_coding","Wikipedia: Vibe coding","cs-term","community-consensus","AI-assisted coding: you prompt an LLM and accept generated code on 'vibes'. Coined by Andrej Karpathy Feb 2025; Collins Word of the Year 2025; in Merriam-Webster slang. STRESS on first word: VYBE-koh-ding. Key for non-natives: 'vibe' has a long i and rhymes with 'tribe' — NOT 'vib'."],
  ["cartesia","/kɑrˈtiʒə/","kar tee zhuh","/kɑrˈtiziə/","kar tee zee uh","https://docs.cartesia.ai/build-with-cartesia/sonic-3/custom-pronunciations","Cartesia Docs — Custom Pronunciations","product","creator-clarified","Real-time voice-AI lab (Stanford 2023; Karan Goel, Albert Gu) behind the Sonic TTS models, built on state-space models (SSMs); rising ElevenLabs rival. Name derives from \"Cartesian\" (math). STRESS: kar-TEE-zhuh — soft \"zh\" as in \"vision\". Cartesia's own docs give IPA kʰ ɑ ɹ tʲ i ʒ ɐ, formed by taking \"cartesian\" and replacing the final \"-an\" with an \"uh\" sound."],
  ["bitsandbytes","/ˌbɪts.ən.ˈbaɪts/","bits and bytes","","","https://github.com/bitsandbytes-foundation/bitsandbytes","bitsandbytes GitHub (bitsandbytes-foundation)","tool","community-consensus","k-bit quantization library for PyTorch underpinning 8-bit optimizers, LLM.int8() and 4-bit/NF4 QLoRA. Written as one lowercase token but spoken as three words: BITS-and-BYTES — STRESS on first and last, middle 'and' reduced to schwa. The spelling is the pronunciation; only the concatenation obscures the word boundaries."],
  ["codebuff","/ˈkoʊdbʌf/","kohd buhf","","","https://github.com/CodebuffAI/codebuff","CodebuffAI GitHub repository (CodebuffAI/codebuff)","cli-tool","community-consensus","Open-source multi-agent terminal coding agent by CodebuffAI; benchmarks against Claude Code. Name is \"code\" + \"buff\" (buffed-up / enhanced). STRESS first syllable: CODE-buff. \"buff\" rhymes with \"stuff\"/\"rough\" (NOT \"byoof\"). No creator-documented pronunciation found, but both halves are everyday English words so the reading is unambiguous. Formerly named Manicode."],
  ["toolformer","/ˈtuːlˌfɔːrmər/","tool for mur","","","https://arxiv.org/abs/2302.04761","arXiv 2302.04761 — Toolformer: Language Models Can Teach Themselves to Use Tools (Schick et al., Meta AI)","project","community-consensus","Meta AI paper (Schick et al., 2023): seminal \"LLM teaches itself to use tools/APIs\" work, foundational to tool-calling agents. Portmanteau of \"tool\" + \"-former\" (borrowed from Transformer). STRESS: TOOL-for-mer; \"-former\" rhymes with the end of transFORMER. No creator audio on record, but the construction is unambiguous."],
  ["MLA","/ˌɛm ˌɛl ˈeɪ/","em el ay","","","https://arxiv.org/abs/2405.04434","DeepSeek-V2 paper (arXiv 2405.04434)","acronym","community-consensus","Multi-head Latent Attention, the DeepSeek-V2/V3 attention variant that compresses the KV cache into a latent vector. Spoken as an initialism, letter by letter: em-el-AY (STRESS on the final letter). Not pronounced as a word. Collides with other meanings of MLA (Modern Language Association, etc.), so in ML context spell it out and rely on the surrounding words Multi-head Latent Attention."],
  ["awq","/ɔk/","awk","/ˌeɪ ˌdʌb əl juː ˈkjuː/","ay duh bul yoo kyoo","https://arxiv.org/abs/2306.00978","arXiv 2306.00978 — AWQ: Activation-aware Weight Quantization for LLM Compression and Acceleration (MIT HAN Lab)","acronym","contested","Activation-aware Weight Quantization. Spoken \"awk\" (like the unix tool) or spelled out A-W-Q."],
  ["ratatui","/ˌræ.təˈtu.i/","rat uh too ee","","","https://github.com/ratatui/ratatui","ratatui GitHub README (official)","tool","creator-clarified","Dominant Rust terminal-UI crate (powers gitui and many TUIs); community fork of tui-rs (2023). Official README documents the IPA ˌræ.təˈtu.i; named after the dish/Pixar film Ratatouille. STRESS: rat-uh-TOO-ee (primary stress on TOO)."],
  ["CodeAct","/ˈkoʊdˌækt/","code act","","","https://arxiv.org/abs/2402.01030","arXiv 2402.01030 — \"Executable Code Actions Elicit Better LLM Agents\" (Wang et al., ICML 2024)","cs-term","community-consensus","Coined compound of \"Code\" + \"Act(ion)\" from the ICML 2024 paper; the agent framework that lets LLMs emit executable Python as their action space (underpins OpenHands / CodeActAgent). Two plain English words; STRESS first syllable: CODE-act (noun-compound stress), not code-ACT."],
  ["subagent","/ˈsʌbˌeɪdʒənt/","sub ay jent","","","https://code.claude.com/docs/en/sub-agents","Claude Code Docs — Create custom subagents","cs-term","community-consensus","Compound of \"sub-\" + \"agent\"; a specialized AI assistant that runs in its own context window, used heavily in Claude Code, the Claude Agent SDK, and agentic-coding tooling. STRESS: SUB-ay-jent — primary on \"sub\", \"agent\" keeps its /ˈeɪdʒənt/ (\"ay-jent\"); the \"g\" is soft (j), not hard. Spelled as one word in the official docs."],
  ["tongyi","/ˈtʊŋˈji/","tohng yee","","toong yee","https://en.wikipedia.org/wiki/Qwen","Wikipedia: Qwen (通义千问 / Tōngyì Qiānwèn)","product","community-consensus","Alibaba's Tongyi (通义) brand umbrella over Qwen / Tongyi Qianwen (通义千问, pinyin Tōngyì Qiānwèn), surfaced across Alibaba Cloud Model Studio and Hugging Face. Pinyin Tōngyì: tōng (通, rounded vowel of English \"song\") + yì (义, \"yee\"). STRESS-pattern: TOHNG-yee, roughly even with a slight lift on the first syllable. English speakers often mangle it as \"tongue-ee\" or \"tahn-jee\"; the o is the rounded \"ong\" of \"song,\" not \"tongue.\""],
  ["watchexec","/ˈwɒtʃ.ɛɡˌzɛk/","wotch eg zek","","","https://github.com/watchexec/watchexec","watchexec/watchexec — GitHub (official repo)","cli-tool","community-consensus","Cross-platform Rust file-watcher that runs a command on file changes (alternative to entr/nodemon). Name = \"watch\" + \"exec\" (execute). The \"exec\" suffix follows dev-tooling convention (cf. the exec syscall / shell builtin): \"eg-ZEK\", not \"ex-eck\". STRESS: WOTCH-eg-zek (primary on first syllable, secondary on -ZEK). No official creator pronunciation FAQ exists, but the compound is unambiguous."],
  ["NF4","/ˌɛn ɛf ˈfɔːr/","en eff four","","","https://arxiv.org/abs/2305.14314","QLoRA: Efficient Finetuning of Quantized LLMs (arXiv 2305.14314)","acronym","community-consensus","4-bit NormalFloat, the information-theoretically-optimal 4-bit datatype introduced in the QLoRA paper (Dettmers et al., 2023) and shipped in bitsandbytes for quantized fine-tuning. Read as an initialism plus the digit: N-F-FOUR. \"NF\" = NormalFloat, \"4\" = 4-bit. Main stress on FOUR. Not \"niff-four\"."],
  ["reflexion","/rɪˈflɛkʃən/","rih flek shun","","","https://www.oxfordlearnersdictionaries.com/us/definition/english/reflexion","Oxford Learner's Dictionaries — reflexion","cs-term","community-consensus","Reflexion is a foundational LLM-agent self-reflection technique (Shinn et al., 2023, \"Reflexion: Language Agents with Verbal Reinforcement Learning\", arXiv:2303.11366), cited across agent frameworks. Despite the 'x' spelling it is pronounced exactly like \"reflection\": rih-FLEK-shun. STRESS on second syllable (FLEK). The 'x' here is /kʃ/, not /ks/ + separate vowel — do not say \"re-FLEX-ion\"; non-natives sometimes second-guess against \"reflection\" but the two are homophones — \"reflexion\" is just the older British orthography. IPA per Oxford Learner's Dictionary /rɪˈflekʃn/."],
  ["FlashAttention","/ˌflæʃ əˈtɛnʃən/","flash uh ten shun","","","https://arxiv.org/abs/2205.14135","arXiv 2205.14135 — FlashAttention: Fast and Memory-Efficient Exact Attention with IO-Awareness (Dao et al.)","project","community-consensus","IO-aware exact-attention GPU kernel (Dao-AILab; FlashAttention-2/3) baked into vLLM, TGI, TensorRT-LLM, PyTorch SDPA. Spoken as the two English words \"flash\" + \"attention\" run together, one word in writing. STRESS: secondary on FLASH, primary on -TEN- (flash-uh-TEN-shun). Non-native speakers hesitate on the flash+attention compound; pronunciation is just the plain English words."],
  ["exaone","/ˈɛks.eɪ.wʌn/","ex ay wun","","","https://huggingface.co/LGAI-EXAONE","LG AI Research — EXAONE HuggingFace org page","product","community-consensus","LG AI Research's open-weight LLM/LMM family (EXAONE 4.0/4.5, K-EXAONE; 2025-2026). Name is an acronym, EXpert AI for EveryONE, so it parses EX-A-ONE. STRESS: EX-a-wun (first syllable). NOT 'exa-ONE' like the SI prefix, NOT 'ex-AY-one.' Acronym documented on LG's HF org page; no explicit spoken-pronunciation quote, hence community-consensus."],
  ["RadixAttention","/ˈreɪdɪks əˌtɛnʃən/","ray diks uh ten shun","/ˈrædɪks əˌtɛnʃən/","rad iks uh ten shun","https://www.lmsys.org/blog/2024-01-17-sglang/","LMSYS Org Blog — \"Fast and Expressive LLM Inference with RadixAttention and SGLang\"","cs-term","community-consensus","SGLang's automatic KV-cache reuse mechanism — a radix tree over the KV cache for prefix sharing; coined by LMSYS (2024). Compound of \"radix\" + \"attention\". STRESS: RAY-diks-uh-TEN-shun (primary on RAY, secondary on TEN). \"radix\" is /ˈreɪdɪks/ (RAY-diks, the standard dictionary form per Wiktionary/Cambridge), NOT \"ra-dicks\" or \"ra-tix\"; final cluster is \"-ks\" not \"-tx\". Often mispronounced by non-native devs as \"ratix\"/\"radicks\". Alt /ˈrædɪks/ (RAD-iks) is a secondary variant."],
  ["mise","/miːz/","meez","","","https://mise.jdx.dev/about.html","mise official docs — About page","cli-tool","creator-clarified","Rust polyglot version manager + task runner by Jeff Dickey (jdx); the asdf successor. Name is short for the French culinary term \"mise-en-place.\" Official docs: `mise` (pronounced \"meez\"), rhymes with \"cheese.\" One syllable, voiced final z. Common wrong guesses: \"my-z\", \"mice\", \"miz.\""],
  ["reka","/ˈrɛkə/","reck uh","/ˈriːkə/","ree kuh","https://arxiv.org/abs/2404.12387","Reka Core, Flash, and Edge technical report (arXiv 2404.12387)","product","contested","Reka AI — multimodal frontier-model lab (Reka Core / Flash / Edge). Reka publishes no official pronunciation, so usage is genuinely split. The name evokes the word for 'river' in two languages that pronounce it differently: South Slavic река gives REK-uh (short e), while Hungarian Réka gives REE-kuh (long ee); English speakers also default to REE-kuh. STRESS on first syllable: REK-uh or REE-kuh."],
  ["swe-agent","/ˈswiː ˌeɪdʒənt/","swee ay jent","/ˌɛs ˌdʌbəljuː ˈiː ˌeɪdʒənt/","ess dubble yoo ee ay jent","https://arxiv.org/abs/2405.15793","arXiv 2405.15793 — SWE-agent: Agent-Computer Interfaces Enable Automated Software Engineering (Princeton/Stanford, NeurIPS 2024)","project","contested","Princeton/Stanford autonomous coding agent (Yang, Jimenez, Press et al.); \"SWE\" = software engineering. Pronunciation is genuinely split: most ML/coding-agent speakers say it as one syllable \"SWEE\" (rhymes with \"free\"), but spelling it out \"S-W-E agent\" is also common. No creator/docs/FAQ documents an official reading (SWE-bench FAQ and SWE-agent README both silent), so marked contested; the \"swee\" form is the more frequent spoken default and is used as the primary respelling. STRESS: SWEE-ay-jent."],
  ["GQA","/ˌdʒiː kjuː ˈeɪ/","jee kyoo ay","","gee kyoo ay","https://arxiv.org/abs/2305.13245","arXiv: GQA: Training Generalized Multi-Query Transformer Models from Multi-Head Checkpoints","acronym","community-consensus","Grouped-Query Attention — the default attention in Llama 2/3, Qwen, Gemma, GPT-OSS. Read as an initialism, letter by letter: G-Q-A, jee-kyoo-AY, STRESS on the final letter. Said-as-a-word never caught on because the Q has no following vowel, so spelling it out is the dominant convention in papers, model cards, and talks."],
  ["egui","/ˈiːɡuːi/","ee gooey","","","https://github.com/emilk/egui/blob/main/README.md","egui official README (emilk/egui)","project","creator-clarified","Rust immediate-mode GUI library by Emil Ernerfeldt (@emilk). README states verbatim: \"pronounced as 'e-gooey'. Please don't write it as 'EGUI'.\" Lowercase, like \"e\" + the word \"gooey\". STRESS: EE-gooey (first syllable). Often mispronounced \"ee-gwee\" or spelled out E-G-U-I."],
  ["seedream","/ˈsiːdriːm/","seed reem","","","https://seed.bytedance.com/en/seedream4_5","ByteDance Seed — Seedream 4.5 official page","product","community-consensus","ByteDance Seed's text-to-image model (Seedream 4.0/4.5, 2025-2026; 4K). Portmanteau of Seed + dream, parallel to siblings Seedance (Seed+dance, video) and SeedEdit — so SEED-reem, not see-DREEM. STRESS: SEED-reem (primary stress on first syllable). The Seed prefix is ByteDance's research division."],
  ["mastra","/ˈmæstrə/","mass truh","/ˈmɑːstrə/","mah struh","https://github.com/mastra-ai/mastra","Mastra GitHub README (mastra-ai/mastra)","project","community-consensus","Open-source TypeScript AI agent framework from the ex-Gatsby team (YC-backed, 1.0 in early 2026). Coined name; etymology undocumented. Dominant English reading is MASS-truh — short A as in 'master', stress on the first syllable. A spelling-pronunciation MAH-struh is sometimes heard; no documented creator FAQ resolves it, hence community-consensus. STRESS: MASS-truh."],
  ["ALiBi","/ˈæləbaɪ/","al uh by","","","https://arxiv.org/abs/2108.12409","arXiv 2108.12409 — Train Short, Test Long: Attention with Linear Biases (ALiBi), Press et al., ICLR 2022","cs-term","community-consensus","ALiBi = Attention with Linear Biases, a transformer position method used in BLOOM and MPT. The camelCase ALiBi cues that it reads as the everyday English word \"alibi\" (STRESS: AL-uh-by, first syllable) — not spelled out A-L-I-B-I, and the \"-bi\" is long-i (\"by\"), not \"bee\". Paper/GitHub don't document the pronunciation, so community-consensus, but the wordplay is unambiguous."],
  ["aya","/ˈɑːjə/","ah yah","/ˈaɪə/","eye uh","https://cohere.com/research/aya","Cohere Labs — Aya research initiative","product","community-consensus","Cohere Labs' open-science multilingual LLM family (Aya 101 / Aya 23 / Aya Expanse / Aya Vision / Tiny Aya), up to 101 languages, Apache-2.0. Named after the Twi (Ghana) word 'aya' = 'fern', an Adinkra symbol of endurance and resourcefulness (per Cohere's announcements). Standard reading is AH-yah (/ˈɑːjə/), matching the Twi/Akan and common given-name pronunciation. STRESS first syllable: AH-yah. Some English speakers anglicize it to EYE-uh, but the fern/Twi origin points to AH-yah."],
  ["fsdp","/ˌɛf ˌɛs ˌdiː ˈpiː/","eff ess dee pee","","","https://docs.pytorch.org/tutorials/intermediate/FSDP_tutorial.html","PyTorch Tutorials — Getting Started with Fully Sharded Data Parallel (FSDP)","acronym","community-consensus","Fully Sharded Data Parallel — PyTorch's ZeRO-style multi-GPU training strategy that shards parameters, gradients, and optimizer states across ranks. Initialism, spelled out letter-by-letter: EFF-ESS-DEE-PEE (no widely-used word pronunciation). Central to multi-GPU/LLM training docs since 2022; FSDP2 is the current rewrite."],
  ["deepgemm","/ˈdiːp ˌdʒɛm/","deep jem","/ˌdiːp ˌdʒiː iː ɛm ˈɛm/","deep jee ee em em","https://github.com/deepseek-ai/DeepGEMM","DeepGEMM GitHub repository (deepseek-ai/DeepGEMM)","project","contested","DeepSeek's FP8/FP4 GEMM kernel library for Hopper/Blackwell, used as a MoE backend by vLLM/SGLang. \"Deep\" + \"GEMM\" (General Matrix Multiply). Pronunciation is genuinely split: most HPC/BLAS practitioners say GEMM as a single word rhyming with \"gem\"/\"hem\" (mirroring how S-GEMM = \"ess-jem\", D-GEMM = \"dee-jem\" are spoken), giving DEEP-jem. Others spell it out, deep-G-E-M-M. README gives no phonetic guidance. STRESS: DEEP-jem."],
  ["hailuo","/ˈhaɪˌlwɔ/","high lwaw","/ˈhaɪˌloʊ/","high low","https://en.wiktionary.org/wiki/%E6%B5%B7%E8%9E%BA","Wiktionary — 海螺 (hǎiluó), Mandarin IPA /xaɪ̯ lu̯ɔ/","product","community-consensus","Hailuo AI is MiniMax's text/image-to-video generator (Hailuo 2.3, Media Agent; 2025). Name romanizes Chinese 海螺 hǎiluó (\"conch / sea snail\"), hence the English nickname \"Conch Video.\" STRESS: HIGH-lwaw. Two syllables: \"hai\"=\"high,\" \"luo\"=pinyin [lwɔ] — a single glide-syllable like \"law\" with a w-onset, NOT three beats \"loo-oh.\" Common anglicized form is \"HIGH-low\" (/haɪloʊ/), shown as the alt. Mandarin tones hǎi (3rd) + luó (2nd); English speakers can ignore tone."],
  ["GPTQ","/ˌdʒiː piː tiː ˈkjuː/","jee pee tee kyoo","","","https://arxiv.org/abs/2210.17323","Frantar et al., \"GPTQ: Accurate Post-Training Quantization for Generative Pre-trained Transformers\" (arXiv:2210.17323)","acronym","community-consensus","Post-training weight quantization method for LLMs (\"GPT\" + \"Q\" for quantization). An initialism, spelled out letter-by-letter: jee-pee-tee-KYOO, primary stress on the final Q. The \"GPT\" prefix is read like GPT-4 (not \"gee-putt\"). Not pronounced as a single word."],
  ["hedra","/ˈhɛdrə/","hed ruh","/ˈhiːdrə/","hee druh","https://www.hedra.com/company","Hedra — Company / About page (a16z-backed AI video startup behind Character-3)","product","contested","Hedra AI — a16z-backed digital-human / talking-avatar startup (Character-3 omnimodal model; $32M Series A, May 2025; 10M+ videos generated). Name = Greek 'hedra' (ἕδρα, 'seat/base'), which standalone reads HED-ruh — Behind the Name lists [ˈhɛdrə]. STRESS: HED-ruh. No founder pronunciation on record; the HEE-druh variant (/ˈhiːdrə/) circulates by analogy with compounds like polyHEEdron / dodecaHEEdron, but for the bare name HED-ruh is the dictionary-backed reading. CONTESTED — no official guidance."],
  ["seedance","/ˈsiːdæns/","seed dance","","","https://seed.bytedance.com/en/seedance","ByteDance Seed — Seedance official page","product","community-consensus","ByteDance's AI video-generation model family (Seedance 1.0 / 2.0, 2026); the video-side sibling of the Seedream image model, both under ByteDance's \"Seed\" foundation-model brand. Portmanteau of Seed + dance. STRESS: SEED-dance — say \"seed\" then \"dance\", NOT \"see-dance\". No documented creator pronunciation quote, but the Seed-prefix branding makes the split unambiguous across docs."],
  ["agentless","/ˈeɪdʒəntləs/","ay jent less","","","https://arxiv.org/abs/2407.01489","arXiv 2407.01489 — \"Agentless: Demystifying LLM-based Software Engineering Agents\"","cs-term","community-consensus","Coined in the OpenAutoCoder/SWE-bench paper for an approach that solves coding tasks WITHOUT an autonomous agent loop — the deliberate antonym of \"agentic\". STRESS stays on the first syllable: AY-jent-less, not uh-JENT-less."],
  ["nccl","/ˈnɪkəl/","nik uhl","","","https://docs.nvidia.com/deeplearning/nccl/user-guide/docs/overview.html","NVIDIA NCCL Developer Guide — Overview","product","creator-clarified","NVIDIA Collective Communications Library — GPU collective comms (all-reduce, all-gather) for distributed ML training. Official docs: \"NCCL, pronounced 'Nickel'\". Said like the coin/metal: NIK-uhl, stress on first syllable. Non-obvious from the letters N-C-C-L."],
  ["pythagora","/pɪˈθæɡərə/","pih thag uh ruh","/paɪˈθæɡərə/","pie thag uh ruh","https://www.pythagora.ai/","Pythagora official site","product","community-consensus","AI dev platform / VS Code + Cursor extension and company (YC W24) behind GPT Pilot. Name = the Greek mathematician Pythagoras (/pɪˈθæɡərəs/) minus the final -s. STRESS on second syllable: pih-THAG-uh-ruh. First syllable is short 'pih' in the US reading; the long-'pie' first syllable (alt) mirrors the standard British reading of Pythagoras. No creator-documented pronunciation found — inferred from the established English reading of Pythagoras."],
  ["ZeRO","/ˈzɪroʊ/","zeer oh","/ˈziːroʊ/","zee roh","https://www.deepspeed.ai/tutorials/zero/","DeepSpeed — Zero Redundancy Optimizer (ZeRO) tutorial","acronym","community-consensus","DeepSpeed's ZeRO = \"ZEro Redundancy Optimizer\" (Microsoft, arXiv:1910.02054). Stylized capitalization (capital Z and O) signals it reads as the English word \"zero\" — identical to the number, NOT spelled out Z-E-R-O. STRESS: ZEER-oh. Stages are ZeRO-1/2/3 (\"zero one/two/three\"). Distinct from existing \"zero-shot\"."],
  ["MQA","/ˌɛm ˌkjuː ˈeɪ/","em kyoo ay","","","https://arxiv.org/abs/2305.13245","arXiv 2305.13245 (GQA paper, defines/compares MQA)","acronym","community-consensus","Multi-Query Attention — the single-KV-head attention variant that GQA generalizes; referenced in serving docs like TensorRT-LLM. Initialism read letter-by-letter, not as a word: STRESS final letter, em-kyoo-AY, exactly parallel to GQA. The expansion 'multi-query attention' is never pronounced."],
  ["pixi","/ˈpɪksi/","pik see","","pixie","https://github.com/prefix-dev/pixi","prefix-dev/pixi GitHub README","cli-tool","community-consensus","Rust-based cross-platform conda/PyPI package & environment manager from prefix.dev (rising 2025-2026 Python/data-science workflow tool). Reads as the English word \"pixie\" — STRESS first syllable: PIK-see, rhymes with \"fixie.\" Not \"pix-eye.\" No official creator pronunciation quote located; based on the unambiguous English reading of the spelling. CLI invoked lowercase as `pixi`."],
  ["chezmoi","/ʃeɪ mwa/","shay mwa","","","https://www.chezmoi.io/user-guide/frequently-asked-questions/design/","chezmoi official FAQ (Design)","cli-tool","creator-clarified","CLI dotfiles manager. Name = French \"chez moi\" (\"at my house\"). Official FAQ documents the pronunciation as /ʃeɪ mwa/ \"shay-mwa\". Non-obvious because the spelling looks English/German; the \"z\" is silent and \"oi\" is the French [wa], not English \"oy\"."],
  ["exl2","/ˌiː ɛks ɛl ˈtuː/","ee eks el too","","","https://github.com/turboderp-org/exllamav2","turboderp-org/exllamav2 (GitHub README)","product","community-consensus","Mixed-bitrate quantization format native to the ExLlamaV2 (turboderp) local-LLM inference library; the name is a contraction of ExLlamaV2 (EX-L + 2). Spelled out letter-by-letter \"E-X-L-TWO\" in local-LLM communities, not read as \"excel-two\". STRESS on TWO. File extension/suffix seen as .exl2 on Hugging Face quants."],
  ["codestral","/koʊˈdɛstrəl/","koh dess truhl","/ˈkoʊdəstrəl/","koh duh struhl","https://mistral.ai/news/codestral/","Mistral AI — Codestral announcement","product","community-consensus","Mistral's 22B code-generation model (released May 2024) with a fill-in-the-middle endpoint, widely used in IDE autocomplete (Continue.dev, Tabnine). The name is reported to be inspired by \"orchestral\" (the model harmonizing coding tasks), blended with \"code\" + the company name \"Mistral.\" STRESS: koh-DESS-truhl — primary stress on the second syllable, by analogy with orchestral (or-KESS-truhl). A code-forward first-syllable reading KOH-duh-struhl (keeping the embedded \"code\" audible, echoing MISS-truhl) is also heard. Official docs give no phonetic guidance."],
  ["koka","/ˈkoʊkə/","koh kuh","/ˈkoʊkɑː/","koh kah","https://koka-lang.github.io/koka/doc/book.html","The Koka Programming Language (official book/docs)","project","community-consensus","Microsoft Research functional language with algebraic effect handlers (Daan Leijen). Name from Japanese 効果 (kōka) \"effect/effectiveness\" — matching its effect-typing focus. STRESS first syllable: KOH-kuh, long-o then schwa. Japanese-faithful variant is KOH-kah (koh kah)."],
  ["mentat","/ˈmɛntæt/","men tat","","","https://mentat.ai/","Mentat (AbanteAI) official site","tool","community-consensus","AI coding tool by AbanteAI — currently MentatBot, a GitHub-native coding agent (earlier archived CLI shared the name). Name borrowed from the \"Mentats\" (human computers) of Frank Herbert's Dune, from Latin mentis / mentation. STRESS-pattern: MEN-tat (first syllable). \"tat\" rhymes with \"cat\"; \"men\" rhymes with \"ten\"."],
  ["nvlink","/ˌɛnˈviː lɪŋk/","en vee link","","","https://en.wikipedia.org/wiki/NVLink","Wikipedia — NVLink","product","community-consensus","NVIDIA's GPU-to-GPU interconnect (constant in GB200/H100 cluster talk). The \"NV\" prefix is the NVIDIA initialism, read as the letters N-V (\"en-vee\"), then plain \"link\": en-vee-LINK. Same NV-prefix pattern as NVSwitch. NOT \"nuv-link\" or \"en-vid-ee-uh link\" — a common non-native slip. STRESS: en-vee-LINK. No official FAQ documents the pronunciation; letter-initialism reading is universal in the community."],
  ["cutlass","/ˈkʌtləs/","kut luhs","","","https://github.com/NVIDIA/cutlass","NVIDIA/cutlass GitHub repo","project","community-consensus","NVIDIA's CUDA C++ GEMM/linear-algebra template library; kernel backend behind vLLM, FlashInfer, and many 2025 LLM-serving stacks. The name is an acronym (CUDA Templates for Linear Algebra Subroutines and Solvers) deliberately landing on the sword 'cutlass' — say it exactly like that word. STRESS first syllable: KUT-luhs. NOT 'CUDA-lass' or 'cut-LASS'. Dictionary IPA /ˈkʌtləs/ (Oxford/Cambridge/Collins, same in BrE and AmE)."],
  ["rmsnorm","/ˌɑːr ɛm ɛs ˈnɔːrm/","ar em ess norm","","","https://arxiv.org/abs/1910.07467","Zhang & Sennrich, \"Root Mean Square Layer Normalization\", arXiv:1910.07467","cs-term","community-consensus","RMSNorm = Root Mean Square (Layer) Normalization, the normalization used in Llama/Mistral and most modern LLMs. Spoken as a compound: the \"RMS\" part is spelled out letter-by-letter (ar-em-ess), then \"norm\" said as the word. STRESS on NORM: \"ar-em-ess NORM\". No source documents an explicit creator pronunciation, but the letter-spelled-acronym + \"norm\" reading is universal in talks and writeups, hence community-consensus."],
  ["PagedAttention","/ˈpeɪdʒd əˈtɛnʃən/","payjd uh ten shun","","","https://arxiv.org/abs/2309.06180","arXiv 2309.06180 — Efficient Memory Management for Large Language Model Serving with PagedAttention","cs-term","community-consensus","vLLM's core attention algorithm, named after OS virtual-memory PAGING. Two parts: \"paged\" + \"attention\". STRESS: PAYJD uh-TEN-shun. The hazard is \"paged\" — it is /peɪdʒd/ (rhymes with \"caged\", one syllable, voiced -jd cluster), NOT two-syllable \"page-ed\". From the verb \"to page\" the KV cache into fixed-size blocks. Common in inference-infra discussion 2023-2026."],
  ["maturin","/ˈmætʊrɪn/","mat uh rin","/ˈmætjʊrɪn/","mat yuh rin","https://github.com/PyO3/maturin","PyO3/maturin — official GitHub repo (formerly pyo3-pack)","cli-tool","community-consensus","STRESS first syllable: MAT-uh-rin (short 'a' as in 'mat', NOT ma-TUR-in). PyO3's official CLI to build & publish Rust-based Python wheels (used by polars, pydantic-core, etc.; pip-installable). The README doesn't document a pronunciation, but 'Maturin' is a real French Huguenot given name (cf. Stephen Maturin in O'Brian's Aubrey–Maturin novels), and references consistently put the stress on the FIRST syllable. A yod variant 'MAT-yuh-rin' also occurs."],
  ["krea","/ˈkriːə/","kree uh","","","https://www.krea.ai/","Krea AI official site","product","community-consensus","AI creative suite (image/video/3D generation) and the FLUX.1 Krea open model co-developed with Black Forest Labs (2025). Two-syllable name: KREE-uh — first syllable rhymes with \"free,\" second is a schwa. STRESS on first syllable: KREE-uh. Common ESL trap: KRAY-uh; accepted reading is KREE-uh."],
  ["veo","/ˈviːoʊ/","vee oh","/ˈveɪoʊ/","vay oh","https://deepmind.google/models/veo/","Google DeepMind — Veo","product","contested","Google DeepMind's text-to-video model (Veo 3 / 3.1, 2025), used inside Gemini and Flow. Dominant English reading is VEE-oh; HowToPronounce gives /ˈviːoʊ/. A VAY-oh variant exists, echoing Spanish \"veo\" (I see). No official creator pronunciation is documented, hence contested. STRESS: VEE-oh."],
  ["oxlint","/ˈɒksˌlɪnt/","ox lint","","","https://oxc.rs/docs/guide/usage/linter.html","Oxlint official docs (oxc.rs)","cli-tool","creator-clarified","\"OX-lint\" — the oxc-based linter; ox like the animal, not the letters O-X."],
  ["pixtral","/ˈpɪks trɑːl/","piks trahl","/pɪks ˈtrɑːl/","piks trahl","https://arxiv.org/abs/2410.07073","Mistral AI (Pixtral 12B paper)","product","community-consensus","Mistral AI's multimodal model family (Pixtral 12B, Pixtral Large). Blend of 'pixel' + 'Mistral,' so '-tral' rhymes with sibling Mistral/Mixtral entries (TRAHL, long ah). Front-loaded stress PIKS-trahl is most common; second-syllable piks-TRAHL (matching some Mixtral speakers) also heard. No creator pronunciation guide published."],
  ["ChatGLM","/ˌtʃæt dʒiː ɛl ˈɛm/","chat jee ell em","","","https://github.com/THUDM/ChatGLM-6B","THUDM/ChatGLM-6B GitHub README","product","community-consensus","Zhipu AI / Tsinghua KEG open bilingual model series. Name = \"Chat\" + GLM, where GLM is an initialism for \"General Language Model\" spoken letter-by-letter: chat-G-L-M, NOT read as a word \"glim\". STRESS: chat-jee-ell-EM (final letter takes the beat). Bare \"GLM\" is already in the dict; this is the searched product name."],
  ["nemotron","/ˈniːmoʊˌtrɑːn/","nee moh tron","/ˈnɛməˌtrɑːn/","nem oh tron","https://en.wikipedia.org/wiki/Nemotron","Wikipedia — Nemotron","product","community-consensus","NVIDIA's flagship open LLM family (Nemotron 3: Nano/Super/Ultra, 2025-2026), hybrid Mamba-Transformer MoE for agentic reasoning. Coined name = NVIDIA's NeMo framework (\"NEural MOdules\", said NEE-mo) + the -tron suffix, so the prevailing reading is first-syllable-stressed NEE-moh-tron. Some devs mis-read it as nem-oh-TRON / nuh-MOT-ron; the NeMo etymology favors NEE-moh-tron. No official creator-documented pronunciation in text. STRESS: NEE-moh-tron."],
  ["recraft","/riˈkræft/","ree kraft","","","https://www.recraft.ai/docs/recraft-models/recraft-V3","Recraft docs — Recraft V3","product","community-consensus","Recraft V3 (Oct 2024), a 20B text-to-image model that topped the Artificial Analysis leaderboard for months. Name is the transparent compound re- + craft. STRESS on the root: re-CRAFT (ree-KRAFT), same pattern as the verb 'to recraft' — not RE-craft. No official creator pronunciation documented; natural English reading of the re- prefix compound."],
  ["knip","/ˈknɪp/","kuh nip","","","https://github.com/webpro-nl/knip","Knip official GitHub README (webpro-nl/knip)","tool","creator-clarified","JS/TS unused files/exports/deps detector by Lars Kappert (webpro). README states: \"/ˈknɪp/ means '(to) cut' and is pronounced with a hard K\" (Dutch). The K is NOT silent — say it \"k-nip\", NOT English \"nip\". Single short-i syllable as in \"nip\". macOS `say` silences the K on raw \"knip\", so the respelling uses a light schwa (\"kuh nip\") to force a hard-K onset — closest `say` gets to a true /kn/ cluster."],
  ["ultracode","/ˈʌltrəˌkoʊd/","ul truh code","","","","","cs-term","community-consensus","\"UL-truh-code\" — Claude Code max-effort mode (/effort) that fans work out across many subagents. Plain ultra + code."],
];

const text = readFileSync(tsvPath, "utf8");
const existing = new Set(
  text.split("\n").filter(l => l && !l.startsWith("#"))
    .map(l => l.split("\t")[0].toLowerCase()).filter(w => w && w !== "word")
);
const fresh = rows.filter(r => !existing.has(r[0].toLowerCase()));
const dupes = rows.filter(r => existing.has(r[0].toLowerCase())).map(r => r[0]);
if (dupes.length) console.log(`skipping ${dupes.length} already present: ${dupes.join(", ")}`);
const lines = fresh.map(r => {
  if (r.length !== 10) throw new Error(`row "${r[0]}" has ${r.length} fields, need 10`);
  return r.join("\t");
});
const out = text.endsWith("\n") ? text + lines.join("\n") + "\n" : text + "\n" + lines.join("\n") + "\n";
writeFileSync(tsvPath, out);
console.log(`appended ${fresh.length} entries → data/pronunciations.tsv`);
