#!/usr/bin/env node
// Batch 12: 2025-2026 AI product / model names + ML-systems & tooling jargon
// devs mispronounce — TTS/audio models (Kokoro, Orpheus, Fugatto, Hume), video
// models (Marey, Vidu, Aleph, Rodin), AI coding tools (Kiro, Qodo, Phind, Junie,
// Dyad), inference/compute stack (cuDNN, ROCm, SYCL, GEMM, einsum, Machete,
// Aphrodite, Horovod, Ulysses), and misleading-spelling names (Le Chat, Coze,
// MinIO, Inngest, Vapi, BAML).
// Discovered + adversarially source-verified via a multi-agent workflow, then
// hand-reviewed and cross-checked with Codex (Kokoro primary aligned to its
// model-card phonemization).
// Columns: word, ipa, respelling_us, alt_ipa, alt_respelling_us,
//          source_url, source_label, category, confidence, notes
import { readFileSync, writeFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const repoRoot = join(dirname(fileURLToPath(import.meta.url)), "..");
const tsvPath = join(repoRoot, "data", "pronunciations.tsv");

const rows = [
  ["Aleph","/ˈɑːlɛf/","ah lef","/ˈɑːlɪf/","ah lif","https://en.wiktionary.org/wiki/aleph","Wiktionary — aleph (English pronunciation)","product","community-consensus","Aleph is Runway's July-2025 in-context video model, named after aleph (א), the first letter of the Hebrew/Semitic alphabet. Stress falls on the first syllable: AH-lef, with a broad \"ah\" /ɑː/; the -lif variant (AH-lif) is equally attested. Non-native devs often mis-stress it as \"uh-LEFF\" (second-syllable stress with a reduced first vowel) or \"AY-leff\" with a long-a; both are wrong. Non-obvious because the spelled \"a\" is the open /ɑ/, not a schwa or the English long-a, and Runway's own announcement never states a pronunciation or name origin."],
  ["Aphrodite","/ˌæfrəˈdaɪti/","af ruh die tee","/ˌæfroʊˈdaɪti/","af roh die tee","https://en.wiktionary.org/wiki/Aphrodite","Wiktionary — Aphrodite (US pronunciation)","project","community-consensus","Aphrodite (aphrodite-engine) is PygmalionAI's large-scale LLM inference engine, built on vLLM's PagedAttention and named after the Greek goddess of love. Four syllables with primary stress on the third: af-ruh-DY-tee, ending in a full \"-ee\" sound. Non-native devs mangle it to \"AY-pro-dite\" — but \"aph\" is \"af\" (not \"ayf\"), and the final -e is NOT silent (it's \"ee\"). It's non-obvious because the \"-ite\" ending looks like it should rhyme with \"kite,\" and English speakers instinctively silence a trailing -e. Verified against Wiktionary US IPA /æfɹəˈdaɪti/."],
  ["BAML","/ˈbæməl/","bam uhl","/ˌbiːˌeɪˌɛmˈɛl/","bee ay em el","https://github.com/BoundaryML/baml","BoundaryML/baml — GitHub README","project","contested","BAML is Boundary's (YC) open-source domain-specific language for writing type-safe LLM/agent prompts; .baml files declare typed prompt functions callable from any language. The README's own gloss is the joke \"Basically A Made-up Language\"; it is also widely reported to have originated as \"Boundary AI Markup Language,\" paralleling YAML. Built on the -ML markup-language lineage, so the natural one-word reading is \"bammel\" /ˈbæməl/ — first-syllable stress, rhyming with camel, exactly like YAML→\"yammel\" / SAML→\"sammel.\" No official pronunciation guide exists and many first-time readers instead spell it out B-A-M-L (alt), so it is genuinely split. Non-obvious because the four consonant-heavy letters give no cue that a vowel sits between the M and L; non-native devs also tend to over-articulate the trailing -L."],
  ["Coze","/koʊz/","kohz","","","https://www.merriam-webster.com/dictionary/coze","Merriam-Webster — \"coze\" /ˈkōz/","product","community-consensus","Coze (Chinese 扣子, kòuzi, \"button\") is ByteDance's no-code AI agent and chatbot-building platform, launched in 2024 (open-source Coze Studio at github.com/coze-dev/coze-studio; coze.com). It is ONE syllable, KOHZ — identical to the rare/literary English verb \"coze\" (\"to chat cozily\"), rhyming with \"doze\" and \"rose\"; the trailing \"e\" is silent and there is no second vowel. Non-native devs routinely misread the -oze/-e ending as a two-syllable \"CO-zee\" (like \"cozy\"), which is wrong. It is non-obvious because the spelling looks like it should split, and the Chinese source name kòuzi actually does have two syllables. Pronunciation confirmed against Merriam-Webster (/ˈkōz/) and Dictionary.com (/koʊz/, respelling [kohz], one syllable); no official ByteDance pronunciation statement was found, hence community-consensus rather than creator-clarified."],
  ["cuDNN","/ˈkuː diː ɛn ɛn/","coo dee en en","","","https://developer.nvidia.com/cudnn","NVIDIA Developer — cuDNN (CUDA Deep Neural Network library)","tool","community-consensus","cuDNN is NVIDIA's CUDA Deep Neural Network library, a GPU-accelerated set of primitives (convolution, attention, matmul, pooling, normalization) that underpins PyTorch, TensorFlow, and JAX. Say it COO-dee-en-en: the lowercase 'cu' inherits CUDA's 'coo' sound (as in barra-CUDA), then D-N-N is spelled out letter by letter, with primary stress on COO. Non-native devs commonly misread the prefix as 'see-you' (C-U) or 'cud', which sounds wrong to practitioners. It's non-obvious because 'cu' is a CUDA abbreviation glued onto DNN, not a standalone English syllable."],
  ["Dyad","/ˈdaɪæd/","dye ad","","","https://www.dyad.sh/","Dyad — official site","tool","community-consensus","Dyad is a free, local, open-source AI app builder for power users (a v0 / Lovable / Bolt / Replit alternative), at dyad.sh (GitHub: dyad-sh/dyad). The name is the ordinary English/Greek word \"dyad\" (from Greek δυάς, \"a pair/group of two\"), stressed on the first syllable: DY-ad /ˈdaɪæd/, where \"dy\" is a long-i diphthong like \"die.\" Confirmed by Merriam-Webster, Cambridge, Oxford, and Wiktionary. Non-native devs commonly misread the \"dy-\" as /diː/ and say \"DEE-ad.\" Official site confirms the name but gives no pronunciation guidance; pronunciation is dictionary-backed."],
  ["einsum","/ˈaɪnsʌm/","ine sum","","","https://numpy.org/doc/stable/reference/generated/numpy.einsum.html","NumPy docs — numpy.einsum (Einstein summation convention)","cs-term","community-consensus","Clip of \"Einstein summation\" — the tensor-contraction primitive in NumPy/PyTorch/JAX (np.einsum, torch.einsum); NumPy docs confirm it \"Evaluates the Einstein summation convention on the operands\" (docs state the meaning, not the pronunciation). Stress on the first syllable: INE-sum, where \"ein\" rhymes with the start of Einstein /aɪn/ (like \"wine\"). Non-native devs commonly say \"EEN-sum\" (/iːn/) or \"AYN-sum\" (/eɪn/, as in \"rein\"); the German \"ei\" digraph is /aɪ/, not /iː/ or /eɪ/. Non-obvious because the clipped \"ein-\" hides its origin in the surname Einstein."],
  ["Fugatto","/fuˈɡɑːtoʊ/","foo gah toh","","","https://research.nvidia.com/publication/2025-04_fugatto-1-foundational-generative-audio-transformer-opus-1","NVIDIA Research — Fugatto 1: Foundational Generative Audio Transformer Opus 1","product","community-consensus","Fugatto = \"Foundational Generative Audio Transformer Opus 1,\" NVIDIA's Nov-2024 any-to-any generative audio model (text/audio prompts to create or transform music, voice, and sound). Pronounced foo-GAH-toh, stress on the second syllable (GAH = long \"ah\" as in father), echoing the Italian musical term \"fugato\" (in the manner of a fugue) — NVIDIA doubled the t for the backronym (Italian speakers note the real word is one-t \"fugato\"). NVIDIA never published an explicit pronunciation, so this reading is inferred from the fugato etymon (community-consensus, not creator-clarified). Non-native devs commonly flatten it to FOO-gat-oh or few-GAT-oh, misplacing stress and using a short American \"a.\""],
  ["GEMM","/dʒɛm/","jem","","","https://en.wikipedia.org/wiki/GEMM","Wikipedia — GEMM (General matrix multiply, a BLAS subprogram)","acronym","community-consensus","GEMM stands for GEneral Matrix Multiply, the BLAS Level-3 routine C = αAB + βC and the single most-invoked GPU kernel in deep learning (\"fp8 gemm\", \"grouped gemm\"). One syllable, said exactly like the jewel GEM — /dʒɛm/. The double M just comes from the BLAS function names (sgemm/dgemm/cgemm) and is NOT a geminated or hard sound. Non-native devs often mis-say it as spelled-out \"G-E-M-M\"; it looks like an initialism and the doubled M invites a wrong reading."],
  ["Horovod","/ˈhɔrəvɑd/","hor uh vahd","/həˈroʊvɑd/","huh roh vahd","https://www.uber.com/en-CA/blog/horovod/","Uber Engineering — Meet Horovod","project","community-consensus","Horovod is Uber's open-source distributed deep-learning training framework (TensorFlow, Keras, PyTorch, MXNet) built on the ring-allreduce communication pattern. Uber's engineering blog confirms the name comes from a traditional Russian folk dance in which performers dance with linked arms in a circle — mirroring how the training processes pass gradients around a ring; the blog gives no pronunciation. First-syllable stress (HOR-uh-vahd) is corroborated by community pronunciation guides (e.g. HowToPronounce). Note the Russian original хоровод is actually final-stressed (kho-ro-VOD); English devs anglicize to first-syllable stress, and some mis-guess huh-ROH-vahd (second-syllable)."],
  ["Hume","/hjuːm/","hyoom","","","https://en.wikipedia.org/wiki/David_Hume","Wikipedia — David Hume (surname /hjuːm/)","product","community-consensus","Hume AI is an empathic-voice research lab whose flagship product is EVI (Empathic Voice Interface, a speech-to-speech API through EVI 3 in 2025); it is named after the 18th-century Scottish philosopher David Hume and ships a \"David Hume\" EVI voice. One syllable, stressed HYOOM — a y-glide plus \"oom\", rhyming with \"room\" (/hjuːm/), with a silent trailing e. Non-native devs commonly mangle it into two syllables (\"HYOO-mee\", \"HOO-may\"); the single-syllable /hjuːm/ is non-obvious because the final e is silent and hu- is a y-glide, not \"hoo\"."],
  ["Inngest","/ɪnˈdʒɛst/","in jest","","","https://github.com/inngest/inngest","Inngest — official GitHub repository","product","community-consensus","Inngest is a durable-execution / workflow-orchestration platform for running reliable step functions and orchestrating AI workflows on serverless, servers, or the edge. The name is a stylized spelling of the verb \"ingest\" (it ingests events), so it is said in-JEST — /ɪnˈdʒɛst/ — with a soft g (dʒ) and stress on the SECOND syllable, identical to \"ingest.\" The extra n is purely cosmetic and does not change the sound. Devs seeing the doubled \"nn\" often say INN-guest or force a hard g, which is what makes it non-obvious. The ingest pronunciation is a well-supported community inference from the obvious wordplay; no official creator statement on pronunciation was found."],
  ["Junie","/ˈdʒuːni/","joo nee","","","https://www.jetbrains.com/junie/","JetBrains — Junie official product page","product","community-consensus","Junie is JetBrains' AI coding agent (launched April 2025; moved out of beta to general availability June 17, 2026), running inside JetBrains IDEs (IntelliJ IDEA, PyCharm, WebStorm, GoLand, Rider, CLion, PhpStorm, RubyMine) and as a standalone CLI. Said \"JOO-nee\" — stress on the first syllable, long \"oo\" — exactly like the English given name/nickname Junie (as in the children's-book character Junie B. Jones): \"June\" + \"-ee\". JetBrains has not published an explicit pronunciation, so this reflects the standard name pronunciation (community consensus), corroborated by HowToPronounce (dʒˈuː.ni) and PronounceNames. Non-native devs are misled by the French-looking \"-ie\" tail into \"joo-NYAY\", or read the u with the \"fun\" vowel as \"JUN-ee\"; both are wrong. Non-obvious because the spelling doesn't cue the long-\"oo\" vowel or the front-stressed name."],
  ["Kiro","/ˈkɪroʊ/","keer oh","","","https://kiro.dev/about/","Kiro — official About page (\"Kiro rhymes with hero\")","product","creator-clarified","Kiro is Amazon/AWS's agentic IDE (2025), centered on spec-driven development: it turns prompts into structured requirements, design, and tasks that AI agents implement. Stress on the first syllable — KEER-oh (/ˈkɪroʊ/). The official About page explicitly says the name \"rhymes with hero.\" Non-native devs are pulled by the spelling toward \"KY-roh\" (long-i, like gyro or Cairo), which is wrong; the written i maps to a near-/ee/ vowel, not the long-i diphthong."],
  ["Kokoro","/ˈkoʊkəroʊ/","koh kuh roh","/ˈkoʊkoʊroʊ/","koh koh roh","https://huggingface.co/hexgrad/Kokoro-82M","hexgrad — Kokoro-82M model card (Hugging Face)","product","community-consensus","Kokoro is the viral 82M-parameter, Apache-2.0 open-weight TTS model released in 2025 by hexgrad; the name is the Japanese word 心, meaning 'heart'/'spirit'. The creator's model-card quickstart phonemizes it /kˈOkəɹO/ (Misaki notation, capital O = /oʊ/) = KOH-kuh-roh, with a reduced middle vowel — used here as the primary because it is the only cited source. A flat, even-vowel KOH-koh-roh, closer to the original Japanese 心 (ko-ko-ro), is the common alternate. Non-native devs commonly stress the middle and add an 'or' vowel ('ko-KOR-oh'), which is wrong; stress stays light and front. Model card verified 2026-07: 82M params, Apache 2.0, name meaning, and the /kˈOkəɹO/ phonemization all present."],
  ["Le Chat","/lə ʃɑ/","luh shah","","","https://en.wikipedia.org/wiki/Mistral_AI","Wikipedia — Mistral AI (Le Chat)","product","community-consensus","Le Chat is Mistral AI's consumer chatbot, a French pun since \"chat\" means both \"chat\" and \"cat,\" which went viral in France in early 2025. Say it the French way, luh SHAH: the final t is silent and \"ch\" is /ʃ/ (like English \"sh\"). Wikipedia gives strict French /lə ʃa/; American speakers naturally render the vowel as \"shah\" /ʃɑ/. English devs commonly mangle it as \"lee chat\" or \"luh CHAT\" with a hard English \"ch\" and an audible t. Non-obvious because the spelling looks like the English word \"chat,\" but it is French. (Mistral renamed the app Vibe at the end of May 2026.)"],
  ["Machete","/məˈʃɛti/","muh shet ee","/məˈtʃɛti/","muh chet ee","https://developers.redhat.com/articles/2024/10/14/introducing-machete-mixed-input-gemm-kernel","Red Hat Developer — Introducing Machete (Neural Magic mixed-input GEMM kernel)","project","community-consensus","Neural Magic's mixed-input (w4a16/w8a16) GEMM kernel in vLLM 0.6.2+, optimized for NVIDIA Hopper GPUs; the spiritual successor to the Marlin kernels. Reuses the common English word 'machete' (the blade; a Spanish loanword). Standard General American puts stress on the second syllable — muh-SHET-ee — with 'ch' pronounced /ʃ/ ('sh') and the final -e as 'ee' /i/, not silent. Merriam-Webster and Wiktionary also list a 'ch' variant /məˈtʃɛti/ (muh-CHET-ee). Devs unfamiliar with the word commonly misread it as 'muh-CHEET' (rhyming with 'machine') or 'MATCH-et'. The source names and describes the kernel but gives no pronunciation guidance, so confidence is community-consensus (standard dictionary word), not creator-clarified."],
  ["Marey","/ˈmɛri/","mair ee","/maˈreɪ/","mah ray","https://www.fastcompany.com/91363868/moonvalley-releases-its-power-tool-for-ai-filmmaking","Fast Company — Moonvalley releases Marey (\"pronounced Mary\")","product","community-consensus","Marey is Moonvalley's foundational AI video model (beta March 2025, GA July 2025), trained exclusively on licensed footage and marketed as the first \"commercially safe\" model for professional filmmaking; API available via fal.ai. Named after 19th-century French chronophotographer Étienne-Jules Marey. Fast Company and other press state it is pronounced exactly like the given name \"Mary\" — MAIR-ee, stress on the first syllable. The common mistake is a French-style \"mah-RAY\" (/maˈreɪ/) or spelling-based \"MAR-ee,\" non-obvious because the honoree's French surname is [maʁɛ] (ma-REH) yet the product deliberately anglicizes to \"Mary.\""],
  ["MinIO","/mɪnˈaɪoʊ/","min eye oh","/ˈmɪnioʊ/","min ee oh","https://www.techtarget.com/searchstorage/blog/Storage-Soup/Minio-prepares-new-object-storage-dish-for-2019","TechTarget Storage Soup — founder A.B. Periasamy on the MinIO name","product","creator-clarified","MinIO is a high-performance, S3-compatible object-storage server; the name is short for \"minimal I/O,\" so it is said min-EYE-oh — the \"IO\" is the spelled-out input/output acronym (\"eye-oh\"). Founder/CEO A.B. (Anand Babu) Periasamy has explicitly stated he wants it known as \"Min-IO, as in minimal IO\" (TechTarget, verified). The article confirms the common variant: \"most people pronounce it MIN-EO\" (min-ee-oh, captured as the alt) — devs default to it because \"-io\" reads like an ordinary word ending rather than a spelled-out acronym."],
  ["Orpheus","/ˈɔːrfiːəs/","or fee us","/ˈɔːrfjuːs/","or fyoos","https://en.wikipedia.org/wiki/Orpheus","Wikipedia — Orpheus (IPA /ˈɔːrfiːəs, ˈɔːrfjuːs/)","product","community-consensus","Orpheus is Canopy Labs' 2025 open-source, Llama-3b-based TTS model (repo canopyai/Orpheus-TTS; HF canopylabs/orpheus-3b-*), named after the legendary Greek bard-musician. Stress on the first syllable: OR-fee-us. Non-native devs often shift stress (or-FEE-us) or read 'ph' as /p/ ('OR-pee-us'); 'ph' is /f/ and the accent stays up front. Non-obvious because the classical name is unfamiliar and 'eu' invites a false /juː/ reading — a rarer two-syllable variant OR-fyoos /ˈɔːrfjuːs/ does exist, but OR-fee-us is dominant."],
  ["Phind","/faɪnd/","find","","","https://www.ycombinator.com/companies/phind","Y Combinator — Phind company profile","product","community-consensus","Phind was an AI search engine and coding assistant built for developers (YC S22, founded by Michael Royzen and Justin Wei; the product went inactive in early 2026). The name is a play on \"find,\" with \"Ph\" taking the F sound as in \"phone\" — a single stressed syllable, FIND (/faɪnd/), a homophone of the word \"find.\" Non-native devs sometimes misread the unusual \"Ph\"-before-consonant spelling as \"P-hind\" or split it into two syllables; it is simply pronounced identically to \"find.\" Corroborated by a Latent Space podcast where founder Michael Royzen's spoken \"Phind\" is transcribed as \"Find.\" The pronunciation is universally understood but not explicitly stated in any official source, hence community-consensus."],
  ["Qodo","/ˈkoʊdoʊ/","koh doh","","","https://www.qodo.ai/blog/introducing-qodo-a-new-name-the-same-commitment-to-quality/","Qodo — \"Introducing Qodo (formerly Codium)\" rebrand announcement","product","community-consensus","Qodo (formerly CodiumAI/Codium, rebranded 2024) is an AI code-review and test-generation agent platform. Its official rebrand blog confirms the name is a confluence of \"Quality\" and \"Code\" (and \"quality of development\") — but the blog does NOT state a pronunciation. Said KOH-doh: first syllable like \"code,\" stress on syllable one. Pronunciation is community consensus (howtopronounce lists /ˈkoʊdoʊ/, \"koh-doh\"), consistent with the \"Code\" root — not an explicit creator statement. Non-native devs, thrown by a bare Q with no following U, often overcorrect to KWOH-doh (treating Q like \"queen\"/\"quick\"), but no /kw/ glide belongs here — this Q is a stylized C, not a normal English Q."],
  ["ROCm","/ˈrɑkəm/","rahk em","","","https://en.wikipedia.org/wiki/ROCm","Wikipedia — ROCm","product","community-consensus","ROCm is AMD's open-source GPU-compute software stack — the CUDA equivalent — and the runtime behind AI training/inference on Instinct accelerators (e.g. MI300X). Said \"ROCK-em\" (/ˈrɑkəm/): stress on the first syllable, trailing lowercase 'm' voiced as a light \"em\" (never spelled out); \"rock-M\" is effectively the same sound. Common mistakes: reading it letter-by-letter (R-O-C-M) or giving \"rock\" a wrong vowel (\"Rockham\"/\"Rockcam\"). Non-obvious because the lowercase 'm' disguises the origin \"Radeon Open Compute (platform)\"; per Wikipedia the name no longer functions as a true acronym (Open Compute is a registered trademark)."],
  ["Rodin","/roʊˈdæn/","roh dan","","","https://en.wikipedia.org/wiki/Auguste_Rodin","Wikipedia — Auguste Rodin (English IPA /roʊˈdæn/)","product","community-consensus","Rodin (Hyper3D Rodin) is Deemos Technology's image-to-3D and text-to-3D generative model (2024-2025), named after French sculptor Auguste Rodin. Anglicized as roh-DAN: stress on the SECOND syllable, final '-DAN' rhyming with the name Dan (/dæn/), per Wikipedia's English IPA /roʊˈdæn/. Non-native devs wrongly read it as 'ROH-din' or 'ROD-in' with English spelling stress; it's non-obvious because the French-derived name stresses the final syllable and its nasal ending anglicizes to '-an' rather than '-in'."],
  ["SYCL","/ˈsɪkəl/","sik uhl","","","https://en.wikipedia.org/wiki/SYCL","Wikipedia — SYCL (pronounced \"sickle\")","cs-term","community-consensus","SYCL is a Khronos Group royalty-free C++ standard for heterogeneous/accelerator (GPU) computing, central to Intel oneAPI and CUDA-to-SYCL porting. Pronounced SICK-ul (/ˈsɪkəl/) — a deliberate homophone of the farming tool \"sickle\" — with stress on the first syllable. Non-native devs commonly spell it out \"S-Y-C-L\" or say \"SY-cull\" (/ˈsaɪkəl/), missing that the two-syllable name reads like a real English word. Originally \"System-wide Compute Language\"; since 2020 the creators state it is a name, not an acronym. Pronunciation documented on Wikipedia; no creator/official pronunciation quote located, so labeled community-consensus."],
  ["Ulysses","/juːˈlɪsiːz/","yoo liss eez","","","https://dictionary.cambridge.org/us/pronunciation/english/ulysses","Cambridge Dictionary — Ulysses (US pronunciation)","project","community-consensus","DeepSpeed-Ulysses is Microsoft's sequence-parallelism system for training extreme-long-context Transformers — it partitions input sequences across GPUs and uses an all-to-all collective for distributed attention (arXiv:2309.14509). \"Ulysses\" is the Latin name for Homer's Odysseus. Primary stress is on the second syllable: yoo-LISS-eez. Non-native devs commonly mangle it as \"oo-LISS-es,\" missing that the initial U is /juː/ (\"yoo\") and the -es ending is /iːz/ (\"eez\"). A first-syllable-stress variant (YOO-lih-seez) exists but the second-syllable reading dominates. Non-obvious because it is a classical proper name with irregular English vowels, yet cited constantly in long-context training papers."],
  ["Vapi","/ˈvæpi/","vappy","","","https://www.ycombinator.com/companies/vapi","Y Combinator — Vapi company profile","product","community-consensus","Vapi (YC W21, vapi.ai) is a developer platform for building voice AI agents; co-founded by Jordan Dearsley (CEO) and Nikhil Gupta (CTO) — not a single founder. The name compresses \"Voice API\" (every feature is accessible via its API), confirmed by multiple sources. Stress falls on the FIRST syllable with a short /æ/: VAP-ee, rhyming with \"happy\" (/ˈvæpi/); corroborated by HowToPronounce (/vˈæ.pi/, \"va-pee\"). No official creator pronunciation statement was found, so confidence stays community-consensus. Non-native devs often default to \"VAH-pee\" (/ˈvɑpi/) or \"VAY-pie\" (/ˈveɪpaɪ/) because the bare letters V-A-P-I don't cue the short /æ/. For macOS say, respell as \"vappy\" for a reliable short-a."],
  ["Vidu","/ˈviːduː/","vee doo","","","https://www.newsgd.com/node_1299786306/bf5b26915a.shtml","GDToday — Tsinghua/Shengshu unveil Vidu (name evokes \"Video\" and \"We do\")","product","community-consensus","Vidu is the text-to-video AI model from Beijing Shengshu Technology and Tsinghua University (launched April 2024; Vidu Q1 shipped 2025). Stress falls on the FIRST syllable: VEE-doo. Shengshu chief scientist Zhu Jun explained at the 2024 Zhongguancun Forum that the name evokes \"video\" and the phrase \"we do.\" Common mistake: non-native devs read it as VY-doo (long-i, as in \"vie\") or VID-oo (short-i, as in \"video\"); the correct branded vowel is a long /iː/, which is non-obvious because English \"video\" actually starts with a short-i /vɪd/."],
];

const text = readFileSync(tsvPath, "utf8");
const existing = new Set(
  text.split("\n").filter(l => l && !l.startsWith("#"))
    .map(l => l.split("\t")[0].toLowerCase()).filter(w => w && w !== "word")
);
const fresh = rows.filter(r => !existing.has(r[0].toLowerCase()));
const dupes = rows.filter(r => existing.has(r[0].toLowerCase())).map(r => r[0]);
if (dupes.length) console.log(`skipping ${dupes.length} already present: ${dupes.join(", ")}`);
const lines = fresh.map(r => {
  if (r.length !== 10) throw new Error(`row "${r[0]}" has ${r.length} fields, need 10`);
  return r.join("\t");
});
const out = text.endsWith("\n") ? text + lines.join("\n") + "\n" : text + "\n" + lines.join("\n") + "\n";
writeFileSync(tsvPath, out);
console.log(`appended ${fresh.length} entries \u2192 data/pronunciations.tsv`);
