#!/usr/bin/env python3
"""Maintain data/entry-dates.tsv — the real datePublished / dateModified per entry.

Why this exists: every word page and API JSON used to stamp datePublished AND
dateModified with the BUILD date. So /word/gif claimed it was first published today
and modified today, on every single CI run — which (a) churned ~5,400 files per run
and (b) told Google that all 1,848 entries change daily, which is a freshness signal
nobody should believe.

This walks the git history of data/pronunciations.tsv once to recover, per entry:
  published = the date its row first appeared
  modified  = the date its row's content last actually changed
and stores them next to a content hash. On later runs it only needs the working-tree
TSV: a new slug gets today's date, a slug whose hash changed gets today as `modified`,
and everything else is left alone.

Run from the repo root. Reads/writes data/entry-dates.tsv (committed).
"""
from __future__ import annotations
import hashlib
import re
import subprocess
import sys
from datetime import date
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
DICT = REPO / "data" / "pronunciations.tsv"
OUT = REPO / "data" / "entry-dates.tsv"
SLUG_RE = re.compile(r"[^a-z0-9._-]")
TODAY = date.today().isoformat()


def slugify(word: str) -> str:
    return SLUG_RE.sub("-", word.lower())


def row_hash(cols: list[str]) -> str:
    return hashlib.sha1("\t".join(cols).encode("utf-8")).hexdigest()[:12]


def parse_tsv(text: str) -> dict[str, list[str]]:
    """slug -> the row's columns."""
    rows = {}
    for raw in text.splitlines():
        if not raw or raw.startswith("#"):
            continue
        cols = raw.split("\t")
        if len(cols) < 3 or cols[0] in ("", "word"):
            continue
        rows[slugify(cols[0])] = cols
    return rows


def git(*args: str) -> str:
    return subprocess.run(
        ["git", *args], cwd=REPO, capture_output=True, text=True, check=True
    ).stdout


def bootstrap() -> dict[str, dict]:
    """Recover published/modified from the TSV's git history (oldest commit first)."""
    log = git("log", "--reverse", "--format=%H %ad", "--date=short", "--", str(DICT))
    commits = [l.split(" ", 1) for l in log.splitlines() if l.strip()]
    print(f"  walking {len(commits)} commits of {DICT.name} …", flush=True)

    state: dict[str, dict] = {}
    for sha, day in commits:
        try:
            blob = git("show", f"{sha}:data/pronunciations.tsv")
        except subprocess.CalledProcessError:
            continue
        for slug, cols in parse_tsv(blob).items():
            h = row_hash(cols)
            prev = state.get(slug)
            if prev is None:
                state[slug] = {"published": day, "modified": day, "hash": h}
            elif prev["hash"] != h:
                prev["modified"] = day
                prev["hash"] = h
    return state


def load() -> dict[str, dict]:
    if not OUT.exists():
        return {}
    state = {}
    for line in OUT.read_text(encoding="utf-8").splitlines():
        if not line or line.startswith("#"):
            continue
        parts = line.split("\t")
        if len(parts) != 4:
            continue
        slug, pub, mod, h = parts
        state[slug] = {"published": pub, "modified": mod, "hash": h}
    return state


def main() -> None:
    state = load()
    if not state:
        print("data/entry-dates.tsv missing — bootstrapping from git history.")
        state = bootstrap()

    rows = parse_tsv(DICT.read_text(encoding="utf-8"))
    added = changed = 0
    for slug, cols in rows.items():
        h = row_hash(cols)
        cur = state.get(slug)
        if cur is None:
            state[slug] = {"published": TODAY, "modified": TODAY, "hash": h}
            added += 1
        elif cur["hash"] != h:
            cur["modified"] = TODAY
            cur["hash"] = h
            changed += 1

    # Drop entries no longer in the dictionary.
    for slug in [s for s in state if s not in rows]:
        del state[slug]

    body = "".join(
        f"{slug}\t{state[slug]['published']}\t{state[slug]['modified']}\t{state[slug]['hash']}\n"
        for slug in sorted(state)
    )
    OUT.write_text(
        "# slug\tdatePublished\tdateModified\trow_hash — generated by tools/build-entry-dates.py\n"
        "# Real per-entry dates. Do NOT hand-edit; do NOT stamp pages with the build date.\n"
        + body,
        encoding="utf-8",
    )
    print(f"  {len(state)} entries ({added} new, {changed} modified today) → {OUT.relative_to(REPO)}")


if __name__ == "__main__":
    sys.exit(main())
